### ISSUE TITLE
Cannot install vendors

### ISSUE THREAD

**Issue by fabienlem** [symfony/demo#958]
Hello,

Juste to let you know that the `composer install` command fail with master and previous tags.

```
Fatal error: Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in C:\www\demo\vendor\ocramius\package-versions\src\PackageVersions\Installer.php:62
Stack trace:
#0 phar://C:/bin/src/Composer/Plugin/PluginManager.php(236): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar://C:/bin/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 phar://C:/bin/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 phar://C:/bin/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Pack
```

Regards

**Comment by xabbuh** [comment]
Looks like you are trying to use a PHP version that does not support the `void` return type hint (i.e. < 7.1).

**Comment by javiereguiluz** [comment]
@fabienlem what's the output when you run this command? Thanks!

```bash
$ php -v
```

**Comment by javiereguiluz** [comment]
Closing because of the lack of activity. Hopefully this was fixed by the user.
